### PR TITLE
set up for exe creation

### PR DESCRIPTION
**Pull request by david3214**
Things I had to update.
I had to make sure that our database csv file and all of our images were added to the datas of the spec file
I had to update the paths of everything to go through the data path. This means that it will only show in the exe, you can't run ```python main.py``` anymore.

Commands to run to make your own exe file.
```python -m pip install pyinstaller```
```python -m PyInstaller ExeCreation.spec```

From there the exe file will be under the dist folder

### CODE REVIEW

**Comment by JoshuaJKrueger** [comment]
If we can't run it through python anymore do we want to keep it as a separate branch, have a development branch and a release branch?

**Comment by david3214** [comment]
> If we can't run it through python anymore do we want to keep it as a separate branch, have a development branch and a release branch?

The only problem is it changes a bunch of files. the reason we can't run in it python anymore is that all of the file paths change. At the same time. the command to make an EXE takes almost no time, so I don't think it will be a big issue

**Comment by JoshuaJKrueger** [comment]
That makes sense. Plus vscode is so flex able you can probably make it "compile" and run automatically like with c++; you can still debug with c++, but I'm not sure if we could achieve the same with python

**Comment by david3214** [comment]
True, something we could look into in the future is updating the fetch_resource function to figure out if it was called by the exe or pyhton command, then we could run it either way

**Review by JoshuaJKrueger — APPROVED** [review]
Looks good, and it compiles and runs for me

**Pull request merged**
