### PR TITLE
Permitted info

### PR DESCRIPTION
**Pull request by JoshuaJKrueger**
Added toggle to add employee and admin screens

### CODE REVIEW

**Review by ComputationalPotato — CHANGES_REQUESTED** [review]
the update button can be pressed even if an entry is invalid, which can corrupt the database. the validation also only happens after the user clicks out of the box so if they are in a text box then click on update, the update would be pressed before they can see the error msg

**Comment by JoshuaJKrueger** [comment]
Good catch I completely forgot about blocking the buttons until all the inputs are valid

**Comment by JoshuaJKrueger** [comment]
Should be fixed now

**Comment by david3214** [comment]
The update button doesn't apply the permitted lock attribute on the admin and add employee screens

**Comment by ComputationalPotato** [comment]
Names can still take invalid characters that can corrupt the database. I recommend using `str.isalnum()`  on all inputs to check if they are alphanumeric(this will complain about spaces and other such characters so if they are allowed then they must be removed before using isalnum(), like with `str.replace(" ","")` `str.replace("-","")`

**Review by ComputationalPotato — APPROVED** [review]

**Pull request merged**
